const path = './images/';

export const Images = {
    homeIcon: require(`${path}homeIcon.png`),
    homeIconActive: require(`${path}homeIconActive.png`),
    profileIconActive: require(`${path}profileIconActive.png`),
    profileIcon: require(`${path}profileIcon.png`),
    japanIconActive: require(`${path}japanIconActive.png`),
    japanIcon: require(`${path}japanIcon.png`),
    logo: require(`${path}logo.png`),
    sound: require(`${path}sound.png`),
    like: require(`${path}like.png`),
    unlike: require(`${path}unlike.png`),
    likeActive: require(`${path}likeActive.png`),
    unlikeActive: require(`${path}unlikeActive.png`),
    momo: require(`${path}momo.png`),
    bank: require(`${path}bank.png`),
    edit: require(`${path}edit.png`),
    trash: require(`${path}trash.png`),
    next: require(`${path}next.png`),
    prev: require(`${path}prev.png`),
    note: require(`${path}note.png`),
    menu: require(`${path}menu.png`),
    menuLogo: require(`${path}menuLogo.png`),
    up: require(`${path}up.png`),
    down: require(`${path}down.png`),
};
